// <auto-generated />
using System;
using DoubleYou.Infrastructure.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoubleYou.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("DoubleYou.Domain.Entities.Entities+User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("ID");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("Created_Utc");

                    b.Property<string>("CultureCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Culture_Code");

                    b.Property<int>("FavoriteTopic")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Favorite_Topic");

                    b.Property<bool>("IsDialogShowInstallVoice")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Is_Dialog_Show_Install_Voice");

                    b.Property<string>("TranslationLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Translation_Language");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("DoubleYou.Domain.Entities.Entities+Word", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("ID");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Word");

                    b.Property<DateTime?>("LearnedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("Learned_Date");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Topic");

                    b.HasKey("Id");

                    b.HasIndex("Data");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("LearnedDate");

                    b.HasIndex("Topic");

                    b.ToTable("Words");
                });
#pragma warning restore 612, 618
        }
    }
}
